In [2]:
%matplotlib inline
from copy import deepcopy
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
plt.rcParams['figure.figsize'] = (16, 9)
plt.style.use('ggplot')
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from kmodes.kmodes import KModes

In [17]:
# Importing the dataset
df = pd.read_excel (r'C:\Users\mjanardanan\Desktop\Clustering\test.xlsx') 
df.head(10)a

timeout  EntDow  EntBin  LOS  Cnt   Rev RateDescription  \
0 2018-01-06 13:14:49       6       8    4    1  20.0         Default   
1 2018-01-06 11:08:26       6       5    5    1  42.0         Default   
2 2018-01-06 12:10:55       6       7    4    1  20.0         Default   
3 2018-01-06 22:06:45       6       8   13    1  52.0         Default   
4 2018-01-06 18:15:51       6      10    7    1  20.0         Default   
5 2018-01-06 23:31:44       6      15    7    1  20.0         Default   
6 2018-01-06 17:56:41       6      16    1    1  21.0     BestParking   
7 2018-01-06 21:36:57       6      16    4    1  40.0  Special Events   
8 2018-01-06 21:49:23       6      17    4    1  25.0         Default   
9 2018-01-06 23:38:24       6      20    3    1  40.0  Special Events   

  BoardDescription                       Description   Online EntryPeriod  \
0  Weekend Special         Default - Weekend Special  Offline     Weekend   
1       Main Board              Default - Main Board  Offline     Weekend   
2  Weekend Special         Default - Weekend Special  Offline     Weekend   
3       Main Board              Default - Main Board  Offline     Weekend   
4  Weekend Special         Default - Weekend Special  Offline     Weekend   
5  Weekend Special         Default - Weekend Special  Offline     Weekend   
6              NaN                    BestParking -      BEST     Weekend   
7  Special  Events  Special Events - Special  Events  Offline     Weekend   
8              NaN                        Default -      PARK     Weekend   
9  Special  Events  Special Events - Special  Events  Offline     Weekend   

   LOS_new  day  cluster_old  cluster  cluster5  cluster_sat  kmode cluster  
0        4    6            8        1         0            0              1  
1        5    6            8        8         0            6              7  
2        4    6            8        1         0            6              1  
3       17    6            2        6         2            3              0  
4        7    6            8        8         0            9              2  
5        7    6            6        9         4            9              6  
6        1    6            6        9         4            5              5  
7        4    6            6        9         4            5              1  
8        4    6            6        9         4            5              1  
9        3    6            6        9         4            5              2

In [18]:
#f1 = df['Cnt'].values
f2 = df['EntBin'].values
f3 = df['LOS_new'].values
#f4 = df['Cnt'].values
X = np.array(list(zip(f2, f3)))
X

array([[ 8,  4],
       [ 5,  5],
       [ 7,  4],
       ...,
       [13,  2],
       [14,  3],
       [18,  2]], dtype=int64)

In [19]:


# Number of clusters
#kmeans = KMeans(n_clusters=10)
# Fitting the input data
#kmeans = kmeans.fit(data_transformed)
# Getting the cluster labels
#labels = kmeans.predict(data_transformed)
# Centroid values
#centroids = kmeans.cluster_centers_
#print(labels)
km = KModes(n_clusters=5, init='random',  n_init = 20, max_iter = 500)

clusters = km.fit_predict(X)

# Print the cluster centroids
#print(km.cluster_centroids_)

In [35]:
print(centroids)

[[6.57097872e+03 1.52340426e+01 1.50212766e+01]
 [1.90647000e+05 7.50000000e+00 8.00000000e+00]
 [3.53042000e+04 1.03000000e+01 5.00000000e+00]
 [1.93404063e+04 1.34687500e+01 7.62500000e+00]
 [1.13992810e+03 1.00130719e+01 3.45098039e+01]
 [1.20833000e+05 9.00000000e+00 8.00000000e+00]
 [4.83420000e+04 1.05000000e+01 3.91666667e+00]
 [1.53810000e+05 6.00000000e+00 8.00000000e+00]
 [1.21017692e+04 1.28205128e+01 1.03076923e+01]
 [2.70735333e+04 1.00000000e+01 3.66666667e+00]]


In [20]:
np.savetxt('kmodes.txt', clusters, fmt='%.f')